name: gpu-comparison-tool
channels:
  - conda-forge
dependencies:
  - python=3.9
  - requests
  - pandas
  - boto3
  - google-auth
  - google-auth-httplib2
  - google-auth-oauthlib
  - azure-identity
  - azure-mgmt-compute
  - oci
  - pip
  - pip:
    - python-dotenv==1.0.0
    - -r requirements.txt
