from .models import GCPZone, GCPZoneNames

ZONES: list[GCPZone] = [
    # US Central
    GCPZone(name=GCPZoneNames.US_CENTRAL1_A, carbon_intensity=430),
    GCPZone(name=GCPZoneNames.US_CENTRAL1_B, carbon_intensity=430),
    GCPZone(name=GCPZoneNames.US_CENTRAL1_C, carbon_intensity=430),
    GCPZone(name=GCPZoneNames.US_CENTRAL1_F, carbon_intensity=430),
    # US East
    GCPZone(name=GCPZoneNames.US_EAST1_B, carbon_intensity=560),
    GCPZone(name=GCPZoneNames.US_EAST1_C, carbon_intensity=560),
    GCPZone(name=GCPZoneNames.US_EAST1_D, carbon_intensity=560),
    GCPZone(name=GCPZoneNames.US_EAST4_A, carbon_intensity=322),
    GCPZone(name=GCPZoneNames.US_EAST4_B, carbon_intensity=322),
    GCPZone(name=GCPZoneNames.US_EAST4_C, carbon_intensity=322),
    GCPZone(name=GCPZoneNames.US_EAST5_A, carbon_intensity=322),
    GCPZone(name=GCPZoneNames.US_EAST5_B, carbon_intensity=322),
    GCPZone(name=GCPZoneNames.US_EAST5_C, carbon_intensity=322),
    # US West
    GCPZone(name=GCPZoneNames.US_WEST1_A, carbon_intensity=94),
    GCPZone(name=GCPZoneNames.US_WEST1_B, carbon_intensity=94),
    GCPZone(name=GCPZoneNames.US_WEST1_C, carbon_intensity=94),
    GCPZone(name=GCPZoneNames.US_WEST2_A, carbon_intensity=198),
    GCPZone(name=GCPZoneNames.US_WEST2_B, carbon_intensity=198),
    GCPZone(name=GCPZoneNames.US_WEST2_C, carbon_intensity=198),
    GCPZone(name=GCPZoneNames.US_WEST3_A, carbon_intensity=588),
    GCPZone(name=GCPZoneNames.US_WEST3_B, carbon_intensity=588),
    GCPZone(name=GCPZoneNames.US_WEST3_C, carbon_intensity=588),
    GCPZone(name=GCPZoneNames.US_WEST4_A, carbon_intensity=373),
    GCPZone(name=GCPZoneNames.US_WEST4_B, carbon_intensity=373),
    GCPZone(name=GCPZoneNames.US_WEST4_C, carbon_intensity=373),
    # US South
    GCPZone(name=GCPZoneNames.US_SOUTH1_A, carbon_intensity=321),
    GCPZone(name=GCPZoneNames.US_SOUTH1_B, carbon_intensity=321),
    GCPZone(name=GCPZoneNames.US_SOUTH1_C, carbon_intensity=321),
    # North America
    GCPZone(name=GCPZoneNames.NORTHAMERICA_NORTHEAST1_A, carbon_intensity=2),
    GCPZone(name=GCPZoneNames.NORTHAMERICA_NORTHEAST1_B, carbon_intensity=2),
    GCPZone(name=GCPZoneNames.NORTHAMERICA_NORTHEAST1_C, carbon_intensity=2),
    GCPZone(name=GCPZoneNames.NORTHAMERICA_NORTHEAST2_A, carbon_intensity=47),
    GCPZone(name=GCPZoneNames.NORTHAMERICA_NORTHEAST2_B, carbon_intensity=47),
    GCPZone(name=GCPZoneNames.NORTHAMERICA_NORTHEAST2_C, carbon_intensity=47),
    # Europe
    GCPZone(name=GCPZoneNames.EUROPE_NORTH1_A, carbon_intensity=46),
    GCPZone(name=GCPZoneNames.EUROPE_NORTH1_B, carbon_intensity=46),
    GCPZone(name=GCPZoneNames.EUROPE_NORTH1_C, carbon_intensity=46),
    GCPZone(name=GCPZoneNames.EUROPE_CENTRAL2_A, carbon_intensity=723),
    GCPZone(name=GCPZoneNames.EUROPE_CENTRAL2_B, carbon_intensity=723),
    GCPZone(name=GCPZoneNames.EUROPE_CENTRAL2_C, carbon_intensity=723),
    GCPZone(name=GCPZoneNames.EUROPE_WEST1_B, carbon_intensity=122),
    GCPZone(name=GCPZoneNames.EUROPE_WEST1_C, carbon_intensity=122),
    GCPZone(name=GCPZoneNames.EUROPE_WEST1_D, carbon_intensity=122),
    GCPZone(name=GCPZoneNames.EUROPE_WEST2_A, carbon_intensity=136),
    GCPZone(name=GCPZoneNames.EUROPE_WEST2_B, carbon_intensity=136),
    GCPZone(name=GCPZoneNames.EUROPE_WEST2_C, carbon_intensity=136),
    GCPZone(name=GCPZoneNames.EUROPE_WEST3_A, carbon_intensity=345),
    GCPZone(name=GCPZoneNames.EUROPE_WEST3_B, carbon_intensity=345),
    GCPZone(name=GCPZoneNames.EUROPE_WEST3_C, carbon_intensity=345),
    GCPZone(name=GCPZoneNames.EUROPE_WEST4_A, carbon_intensity=236),
    GCPZone(name=GCPZoneNames.EUROPE_WEST4_B, carbon_intensity=236),
    GCPZone(name=GCPZoneNames.EUROPE_WEST4_C, carbon_intensity=236),
    GCPZone(name=GCPZoneNames.EUROPE_WEST6_A, carbon_intensity=59),
    GCPZone(name=GCPZoneNames.EUROPE_WEST6_B, carbon_intensity=59),
    GCPZone(name=GCPZoneNames.EUROPE_WEST6_C, carbon_intensity=59),
    GCPZone(name=GCPZoneNames.EUROPE_WEST8_A, carbon_intensity=249),
    GCPZone(name=GCPZoneNames.EUROPE_WEST8_B, carbon_intensity=249),
    GCPZone(name=GCPZoneNames.EUROPE_WEST8_C, carbon_intensity=249),
    GCPZone(name=GCPZoneNames.EUROPE_WEST9_A, carbon_intensity=34),
    GCPZone(name=GCPZoneNames.EUROPE_WEST9_B, carbon_intensity=34),
    GCPZone(name=GCPZoneNames.EUROPE_WEST9_C, carbon_intensity=34),
    GCPZone(name=GCPZoneNames.EUROPE_WEST10_A, carbon_intensity=345),
    GCPZone(name=GCPZoneNames.EUROPE_WEST10_B, carbon_intensity=345),
    GCPZone(name=GCPZoneNames.EUROPE_WEST10_C, carbon_intensity=345),
    GCPZone(name=GCPZoneNames.EUROPE_WEST12_A, carbon_intensity=249),
    GCPZone(name=GCPZoneNames.EUROPE_WEST12_B, carbon_intensity=249),
    GCPZone(name=GCPZoneNames.EUROPE_WEST12_C, carbon_intensity=249),
    GCPZone(name=GCPZoneNames.EUROPE_SOUTHWEST1_A, carbon_intensity=131),
    GCPZone(name=GCPZoneNames.EUROPE_SOUTHWEST1_B, carbon_intensity=131),
    GCPZone(name=GCPZoneNames.EUROPE_SOUTHWEST1_C, carbon_intensity=131),
    # Asia
    GCPZone(name=GCPZoneNames.ASIA_EAST1_A, carbon_intensity=451),
    GCPZone(name=GCPZoneNames.ASIA_EAST1_B, carbon_intensity=451),
    GCPZone(name=GCPZoneNames.ASIA_EAST1_C, carbon_intensity=451),
    GCPZone(name=GCPZoneNames.ASIA_EAST2_A, carbon_intensity=360),
    GCPZone(name=GCPZoneNames.ASIA_EAST2_B, carbon_intensity=360),
    GCPZone(name=GCPZoneNames.ASIA_EAST2_C, carbon_intensity=360),
    GCPZone(name=GCPZoneNames.ASIA_NORTHEAST1_A, carbon_intensity=459),
    GCPZone(name=GCPZoneNames.ASIA_NORTHEAST1_B, carbon_intensity=459),
    GCPZone(name=GCPZoneNames.ASIA_NORTHEAST1_C, carbon_intensity=459),
    GCPZone(name=GCPZoneNames.ASIA_NORTHEAST2_A, carbon_intensity=385),
    GCPZone(name=GCPZoneNames.ASIA_NORTHEAST2_B, carbon_intensity=385),
    GCPZone(name=GCPZoneNames.ASIA_NORTHEAST2_C, carbon_intensity=385),
    GCPZone(name=GCPZoneNames.ASIA_NORTHEAST3_A, carbon_intensity=378),
    GCPZone(name=GCPZoneNames.ASIA_NORTHEAST3_B, carbon_intensity=378),
    GCPZone(name=GCPZoneNames.ASIA_NORTHEAST3_C, carbon_intensity=378),
    GCPZone(name=GCPZoneNames.ASIA_SOUTH1_A, carbon_intensity=648),
    GCPZone(name=GCPZoneNames.ASIA_SOUTH1_B, carbon_intensity=648),
    GCPZone(name=GCPZoneNames.ASIA_SOUTH1_C, carbon_intensity=648),
    GCPZone(name=GCPZoneNames.ASIA_SOUTH2_A, carbon_intensity=529),
    GCPZone(name=GCPZoneNames.ASIA_SOUTH2_B, carbon_intensity=529),
    GCPZone(name=GCPZoneNames.ASIA_SOUTH2_C, carbon_intensity=529),
    GCPZone(name=GCPZoneNames.ASIA_SOUTHEAST1_A, carbon_intensity=369),
    GCPZone(name=GCPZoneNames.ASIA_SOUTHEAST1_B, carbon_intensity=369),
    GCPZone(name=GCPZoneNames.ASIA_SOUTHEAST1_C, carbon_intensity=369),
    GCPZone(name=GCPZoneNames.ASIA_SOUTHEAST2_A, carbon_intensity=580),
    GCPZone(name=GCPZoneNames.ASIA_SOUTHEAST2_B, carbon_intensity=580),
    GCPZone(name=GCPZoneNames.ASIA_SOUTHEAST2_C, carbon_intensity=580),
    # Australia
    GCPZone(name=GCPZoneNames.AUSTRALIA_SOUTHEAST1_A, carbon_intensity=501),
    GCPZone(name=GCPZoneNames.AUSTRALIA_SOUTHEAST1_B, carbon_intensity=501),
    GCPZone(name=GCPZoneNames.AUSTRALIA_SOUTHEAST1_C, carbon_intensity=501),
    GCPZone(name=GCPZoneNames.AUSTRALIA_SOUTHEAST2_A, carbon_intensity=456),
    GCPZone(name=GCPZoneNames.AUSTRALIA_SOUTHEAST2_B, carbon_intensity=456),
    GCPZone(name=GCPZoneNames.AUSTRALIA_SOUTHEAST2_C, carbon_intensity=456),
    # South America
    GCPZone(name=GCPZoneNames.SOUTHAMERICA_EAST1_A, carbon_intensity=56),
    GCPZone(name=GCPZoneNames.SOUTHAMERICA_EAST1_B, carbon_intensity=56),
    GCPZone(name=GCPZoneNames.SOUTHAMERICA_EAST1_C, carbon_intensity=56),
    GCPZone(name=GCPZoneNames.SOUTHAMERICA_WEST1_A, carbon_intensity=138),
    GCPZone(name=GCPZoneNames.SOUTHAMERICA_WEST1_B, carbon_intensity=138),
    GCPZone(name=GCPZoneNames.SOUTHAMERICA_WEST1_C, carbon_intensity=138),
    # Africa
    GCPZone(name=GCPZoneNames.AFRICA_SOUTH1_A, carbon_intensity=646),
    GCPZone(name=GCPZoneNames.AFRICA_SOUTH1_B, carbon_intensity=646),
    GCPZone(name=GCPZoneNames.AFRICA_SOUTH1_C, carbon_intensity=646),
    # Middle East
    GCPZone(name=GCPZoneNames.ME_CENTRAL1_A, carbon_intensity=575),
    GCPZone(name=GCPZoneNames.ME_CENTRAL1_B, carbon_intensity=575),
    GCPZone(name=GCPZoneNames.ME_CENTRAL1_C, carbon_intensity=575),
    GCPZone(name=GCPZoneNames.ME_CENTRAL2_A, carbon_intensity=569),
    GCPZone(name=GCPZoneNames.ME_CENTRAL2_B, carbon_intensity=569),
    GCPZone(name=GCPZoneNames.ME_CENTRAL2_C, carbon_intensity=569),
    GCPZone(name=GCPZoneNames.ME_WEST1_A, carbon_intensity=463),
    GCPZone(name=GCPZoneNames.ME_WEST1_B, carbon_intensity=463),
    GCPZone(name=GCPZoneNames.ME_WEST1_C, carbon_intensity=463),
]

ZONES_BY_NAME: dict[GCPZoneNames, GCPZone] = {zone.name: zone for zone in ZONES}